// // Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// // Display this Vue component on Rails View by adding `require('./register')` to app/javascript/application.js
// // Generate a component part by running command `rails generate vue something`

// import Vue from 'vue'
// import App from '@/register.vue'

// document.addEventListener('DOMContentLoaded', () => {
//   document.body.appendChild(document.createElement('register'))
//   const register = new Vue({
//     render: h => h(App)
//   }).$mount('register')
//   console.log({register})
// })